---
title: "Edinburgh Biodiversity"
author: "John Doe"
date: 10/Nov/2021
output: html_document
---
# YAML header format---

title: ""
author: 
date: 10/Nov/2021
output: 
  html_document: 
    toc: true  # to get a table of contents at the top 
    toc_float: true  # so that it never disappears 

# Text format ----

*Italic*

**Bold**

`code` for highlighted words or code 

# Header 1

## Header 2

* list item with a dot

1. list with numbers 

[link](https://www.google.com)

$A = \pi \times r^{2}$ for equations

```{r}
norm <- rnorm(100, mean = 0, sd = 1)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
```


```{r}
edidiv <- read.csv("edidiv.csv")

richness <- 
  edidiv %>%
    group_by(taxonGroup) %>%
    summarise(Species_richness = n_distinct(taxonName))

barplot(richness$Species_richness, 
        names.arg = richness$taxonGroup, 
        xlab = "Taxa", ylab = "Number of species", 
        ylim = c(0,600)
        ) 
```

```{r, fig.width = 4, fig.height = 3}
A <- c("a", "a", "b", "b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A, B)
print(dataframe)
boxplot(B~A,data=dataframe)
```

```{r}
dataframe
```

```{r}
library(knitr)
kable(dataframe, digits = 2)
```

```{r}
library(pander)
plant <- c("a", "b", "c")
temperature <- c(20, 20, 20)
growth <- c(0.65, 0.95, 0.15)
dataframe <- data.frame(plant, temperature, growth)
emphasize.italics.cols(3)   # Make the 3rd column italics
pander(dataframe)           # Create the table
```

| Plant | Temp. | Growth |
|:------|:-----:|-------:|
| A     | 20    | 0.65   |
| B     | 20    | 0.95   |
| C     | 20    | 0.15   |

```{r warning=FALSE}
library(broom)
library(pander)
A <- c(20, 15, 10)
B <- c(1, 2, 3)

lm_test <- lm(A ~ B)            # Creating linear model

table_obj <- tidy(lm_test)      # Using tidy() to create a new R object called table

pander(table_obj, digits = 3)   # Using pander() to view the created table, with 3 sig figs 
```

